-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;
DROP DATABASE IF EXISTS Category;
DROP DATABASE IF EXISTS Product;
DROP DATABASE IF EXISTS Tag;
DROP DATABASE IF EXISTS ProductTag;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;
